common:
  min_behavior_stop_margin: 1.0
  enable_slow_down_planning: true
  safe_distance_margin: 1.5

behavior_determination:
  decimate_trajectory_step_length: 0.5
  max_lat_margin_for_stop: 0.8
  max_lat_margin_for_cruise: 0.5
  obstacle_velocity_threshold_from_stop_to_cruise: 0.1
